class TestData:
    BASE_URL = 'https://www.ozon.ru/'

    """Заголовки окон с соответствующми страницами,"""
    """где нет заголовка раздела на самой странице там заголовок окна"""
    HEADER_OF_WINDOW_MAIN_LOGO = 'Выгодные предложения'
    NAME_OF_BUTTON_CATALOG = "Каталог"
    NAME_OF_BUTTON_ORDERS = "Заказы"
    NAME_OF_BUTTON_TOP_FASHION = "TOP Fashion"
    HEADER_OF_PAGE_FAVORITES = "Товары и списки"
    NAME_OF_BUTTON_FAVORITES = "Избранное"
    HEADER_OF_WINDOW_CART = 'Корзина пуста'
    TOP_FASHION = "TOP Fashion"
    NAME_OF_BUTTON_Premium = "Premium"
    NAME_OF_BUTTON_OZON_TRAVEL = "Билеты и Отели"
    NAME_OF_BUTTON_OZON_KART = "Ozon Карта"
    NAME_OF_BUTTON_LIVE = "LIVE"
    NAME_OF_BUTTON_ACTIONS = "Акции"
    NAME_OF_BUTTON_BRANDS = "Бренды"
    HEADER_OF_WINDOW_OZON_TRAVEL = "Поиск дешёвых авиабилетов"
    HEADER_OF_WINDOW_OZON_KART = "Выгода до 30% c Ozon Картой"
    HEADER_OF_PAGE_OF_ACTIONS = "Акции и спецпредложения"
    HEADER_OF_PAGE_OF_BRENDS = "Все бренды"
    NAME_OF_BUTTON_EXPRESS = "Express"
    HEADER_OF_PAGE_EXPRESS = "Товары с экспресс-доставкой"
    HEADER_OF_PAGE_OF_SHOPS = "Все магазины"
    HEADER_OF_PAGE_OF_ELECTRONICA_MAIN = "Электроника"
    NAME_OF_BUTTON_ELECTRONICA_MAIN = "Электроника"
    NAME_OF_BUTTON_CLOTHES_AND_SHOES = "Одежда и обувь"
    HEADER_OF_CHAPTER_OF_CLOTHES_AND_SHOES = "Женщинам"
    NAME_OF_BUTTON_KIDS_GOODS = "Детские товары"
    HEADER_OF_PAGE_OF_KIDS_GOODS = "Детские товары"
    NAME_OF_BUTTON_HOUSE_AND_GARDEN = "Дом и сад"
    HEADER_OF_PAGE_OF_HOUSE_AND_GARDEN = "Дом и сад"
    HEADER_OF_WINDOW_SELECT_CITY = "Выберите город"
    LIMIT = "Рассрочка"
    NAME_OF_BUTTON_CERTIFICATES = "Сертификаты"
    HEAD_OF_PAGE_CERTIFICATES = "Электронный подарочный сертификат Миллион подарков (3000) ozon"

